"""SCHISM adapter — subprocess wrapper. SPEC §6.1, ADR-0002.

This adapter prepares SCHISM input files from a WEDM case, spawns the SCHISM
executable (or container), and reads ``schout_*.nc`` results back into WEDM.

LTS pin: SCHISM v5.11.0 (ADR-0002).

M3 scope (this iteration): full prepare/run/read_results lifecycle plus
``ol_mode='dry-run'`` that produces all input files but skips the actual
SCHISM invocation, useful for CI without SCHISM installed.

This skeleton is fully testable in environments WITHOUT SCHISM via dry-run.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

logger = logging.getLogger(__name__)

LTS_VERSION = "5.11.0"


@dataclass
class SCHISMRunReport:
    """Outcome of a SCHISM run."""

    work_dir: Path
    return_code: int
    duration_seconds: float
    schout_path: Path | None
    log_path: Path
    dry_run: bool = False


@dataclass(frozen=True)
class SCHISMBoundaryForcingPackage:
    """SCHISM Type-1 boundary forcing files generated by OpenLimno."""

    work_dir: Path
    bctides_path: Path
    flags_path: Path
    manifest_path: Path
    elev_th_path: Path | None
    flux_th_path: Path | None
    n_boundaries: int
    n_elevation_boundaries: int
    n_flux_boundaries: int
    n_times: int


@dataclass(frozen=True)
class SCHISMHydraulicResults:
    """Normalized SCHISM hydraulic results ready for OpenLimno post-processing."""

    dataset: Any
    table: Any
    source_files: tuple[Path, ...]
    n_nodes: int
    n_times: int
    selected_time_index: int | None
    warnings: tuple[str, ...] = ()


@dataclass
class SCHISMAdapter:
    """SCHISM subprocess wrapper.

    Parameters
    ----------
    executable
        Path to SCHISM binary (e.g. ``pschism_TVD-VL``). If None, will look
        for ``OPENLIMNO_SCHISM`` environment variable, then PATH.
    container_image
        OCI image (e.g. ``ghcr.io/openlimno/schism:5.11.0``). If set,
        overrides ``executable`` and runs SCHISM via ``docker run`` /
        ``apptainer run``.
    n_procs
        Number of MPI processes (default 1; SCHISM serial build).
    n_scribes
        Number of SCHISM scribe I/O processes. The v5.11 executable requires
        this as argv[1]; ``0`` is the single-process/no-scribe default.
    timeout_s
        Subprocess timeout in seconds. None = unlimited.
    """

    executable: str | None = None
    container_image: str | None = None
    container_runtime: Literal["docker", "apptainer", "podman"] = "docker"
    n_procs: int = 1
    n_scribes: int = 0
    timeout_s: float | None = None
    lts_version: str = LTS_VERSION

    _input_files: list[str] = field(
        default_factory=lambda: [
            "hgrid.gr3",
            "vgrid.in",
            "param.nml",
            "bctides.in",
            "drag.gr3",
        ]
    )

    # ------------------------------------------------------------------
    # HydroSolver Protocol
    # ------------------------------------------------------------------
    def prepare(
        self,
        case_yaml: str | Path,
        work_dir: str | Path,
        wedm_mesh_path: str | Path | None = None,
        param_overrides: dict[str, Any] | None = None,
    ) -> Path:
        """Stage SCHISM input files in ``work_dir``.

        If ``wedm_mesh_path`` points to a UGRID-2D NetCDF, generates a real
        ``hgrid.gr3`` derived from it. Otherwise writes a clearly-marked
        placeholder. Always writes a usable ``param.nml`` skeleton, single-
        layer ``vgrid.in`` (depth-averaged), and ``bctides.in`` stub.
        """
        work_dir = Path(work_dir).resolve()
        work_dir.mkdir(parents=True, exist_ok=True)
        (work_dir / "outputs").mkdir(exist_ok=True)

        used_real_mesh = False
        hgrid_summary = {"n_open_boundaries": 0, "n_land_boundaries": 0}
        if wedm_mesh_path is not None and Path(wedm_mesh_path).exists():
            try:
                hgrid_summary = _write_hgrid_from_ugrid(
                    Path(wedm_mesh_path), work_dir / "hgrid.gr3"
                )
                used_real_mesh = True
                logger.info("hgrid.gr3 generated from %s", wedm_mesh_path)
            except Exception as e:
                logger.warning(
                    "UGRID → hgrid.gr3 conversion failed: %s; using placeholder",
                    e,
                )

        if not used_real_mesh:
            (work_dir / "hgrid.gr3").write_text(
                "OpenLimno SCHISM placeholder hgrid.gr3\n"
                "0 0\n"  # 0 elements, 0 nodes — runs will fail with clear error
            )

        # SCHISM main parameter file (real, runnable skeleton)
        (work_dir / "param.nml").write_text(_render_param_nml(param_overrides))
        # vgrid.in: minimal two-level SZ grid. SCHISM still requires bottom
        # and surface levels even for OpenLimno's depth-averaged handoff.
        (work_dir / "vgrid.in").write_text(
            "2 ! ivcor: SZ coordinates\n"
            "2 1 100.0 ! nvrt kz h_s\n"
            "Z levels\n"
            "1 -100.0\n"
            "S levels\n"
            "50.0 0.0 1.0 ! h_c theta_b theta_f\n"
            "1 -1.0\n"
            "2 0.0\n"
        )
        # bctides.in template: matches hgrid open-boundary count but leaves
        # forcing flags/series for the modeler or case builder to fill.
        (work_dir / "bctides.in").write_text(
            _render_bctides_template(int(hgrid_summary["n_open_boundaries"]))
        )
        _write_constant_gr3_from_hgrid(
            work_dir / "hgrid.gr3",
            work_dir / "drag.gr3",
            value=0.0025,
            title="OpenLimno constant bottom drag coefficient",
        )

        marker = work_dir / ".openlimno_prepared"
        marker.write_text(
            json.dumps(
                {
                    "case_yaml": str(case_yaml),
                    "lts_version": self.lts_version,
                    "input_files": self._input_files,
                    "real_mesh": used_real_mesh,
                    "wedm_mesh_path": str(wedm_mesh_path) if wedm_mesh_path else None,
                    "hgrid": hgrid_summary,
                }
            )
        )
        logger.info("SCHISM work_dir prepared at %s (real_mesh=%s)", work_dir, used_real_mesh)
        return work_dir

    def run(
        self,
        work_dir: str | Path,
        dry_run: bool = False,
    ) -> SCHISMRunReport:
        """Spawn SCHISM in ``work_dir`` and capture its output.

        ``dry_run=True`` skips the subprocess and returns a synthesized report;
        useful for CI environments without SCHISM installed.
        """
        import time

        work_dir = Path(work_dir).resolve()
        marker = work_dir / ".openlimno_prepared"
        if not marker.exists():
            raise RuntimeError(f"work_dir {work_dir} not prepared; call prepare() first")

        log_path = work_dir / "schism.log"
        start = time.time()

        if dry_run:
            log_path.write_text("DRY RUN — SCHISM not invoked\n")
            return SCHISMRunReport(
                work_dir=work_dir,
                return_code=0,
                duration_seconds=0.0,
                schout_path=None,
                log_path=log_path,
                dry_run=True,
            )

        try:
            cmd = self._build_command(work_dir)
        except RuntimeError as e:
            log_path.write_text(f"SCHISM executable not found: {e}\n")
            return SCHISMRunReport(
                work_dir=work_dir,
                return_code=127,
                duration_seconds=0.0,
                schout_path=None,
                log_path=log_path,
                dry_run=False,
            )
        logger.info("Spawning SCHISM: %s (cwd=%s)", " ".join(cmd), work_dir)

        with log_path.open("w", encoding="utf-8") as logf:
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=work_dir,
                    stdout=logf,
                    stderr=subprocess.STDOUT,
                    timeout=self.timeout_s,
                    check=False,
                )
                rc = proc.returncode
            except subprocess.TimeoutExpired:
                logger.error("SCHISM timeout after %s s", self.timeout_s)
                rc = 124
            except FileNotFoundError as e:
                logger.error("SCHISM executable not found: %s", e)
                rc = 127

        duration = time.time() - start
        try:
            schout = _find_schism_output_files(work_dir)[0]
        except FileNotFoundError:
            schout = None
        return SCHISMRunReport(
            work_dir=work_dir,
            return_code=rc,
            duration_seconds=duration,
            schout_path=schout,
            log_path=log_path,
            dry_run=False,
        )

    def read_results(
        self,
        work_dir: str | Path,
        *,
        time_index: int | None = None,
        h0: float = 0.01,
    ) -> SCHISMHydraulicResults:
        """Read SCHISM NetCDF outputs and normalize depth/velocity fields."""

        return read_schism_hydraulic_results(work_dir, time_index=time_index, h0=h0)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _build_command(self, work_dir: Path) -> list[str]:
        """Build the subprocess argv for the SCHISM run."""
        scribe_arg = str(self.n_scribes)
        if self.container_image:
            # Container path
            mount = f"{work_dir}:/work"
            if self.container_runtime in ("docker", "podman"):
                cmd = [self.container_runtime, "run", "--rm"]
                # --user host-uid:gid keeps container outputs owned by the host
                # user on POSIX. os.getuid/os.getgid don't exist on Windows
                # (Docker Desktop maps users differently), so omit the flag there.
                if hasattr(os, "getuid"):
                    cmd += ["--user", f"{os.getuid()}:{os.getgid()}"]
                cmd += ["-v", mount, "-w", "/work"]
                if self.n_procs > 1:
                    cmd.extend(
                        [
                            "--entrypoint",
                            "mpirun",
                            self.container_image,
                            "-n",
                            str(self.n_procs),
                            "/usr/local/bin/schism",
                            scribe_arg,
                        ]
                    )
                else:
                    cmd.extend([self.container_image, scribe_arg])
                return cmd
            if self.container_runtime == "apptainer":
                return [
                    "apptainer",
                    "run",
                    "--bind",
                    mount,
                    self.container_image,
                    scribe_arg,
                ]
        # Native path
        exe = (
            self.executable
            or os.environ.get("OPENLIMNO_SCHISM")
            or shutil.which("pschism_TVD-VL")
            or shutil.which("schism")
        )
        if not exe:
            raise RuntimeError(
                "No SCHISM executable found. Set executable=, container_image=, "
                "or OPENLIMNO_SCHISM env var. ADR-0002 recommends the OCI container "
                "ghcr.io/openlimno/schism:5.11.0."
            )
        if self.n_procs > 1:
            return ["mpirun", "-n", str(self.n_procs), exe, scribe_arg]
        return [exe, scribe_arg]


def _render_param_nml(overrides: dict[str, Any] | None = None) -> str:
    """Render a SCHISM param.nml namelist with sensible OpenLimno defaults.

    Users can override any value via the ``param_overrides`` dict in
    ``SCHISMAdapter.prepare(..., param_overrides=...)``.
    """
    core: dict[str, Any] = {
        "ipre": 0,  # 0 = run, 1 = pre-process only
        "ibc": 1,  # barotropic mode for OpenLimno's depth-averaged handoff
        "ibtp": 0,  # true barotropic model
        "rnday": 1.0,  # simulation length in days
        "dt": 100.0,  # time step in s
        "msc2": 24,
        "mdc2": 30,
        "ntracer_gen": 0,
        "ntracer_age": 0,
        "sed_class": 1,
        "eco_class": 1,
        "nspool": 36,
        "ihfskip": 864,
    }
    opt: dict[str, Any] = {
        "ihot": 0,  # cold start
        "ics": 1,  # Cartesian coordinates
        "indvel": 1,
        "ihorcon": 0,
        "h0": 0.01,
    }
    schout: dict[str, Any] = {
        "nc_out": 1,
        "iof_hydro(1)": 1,  # elevation
        "iof_hydro(25)": 1,  # zcor
        "iof_hydro(26)": 1,  # depth-averaged velocity
    }

    if overrides:
        for key, value in overrides.items():
            if key in core:
                core[key] = value
            elif key in schout or key.startswith("iof_") or key in {"nc_out", "iof_ugrid"}:
                schout[key] = value
            else:
                opt[key] = value

    return (
        _render_namelist("CORE", core)
        + _render_namelist("OPT", opt)
        + _render_namelist("SCHOUT", schout)
    )


def _render_namelist(name: str, values: dict[str, Any]) -> str:
    lines = [f"&{name}"]
    for k, v in values.items():
        lines.append(f"  {k} = {_format_namelist_value(v)}")
    lines.append("/")
    return "\n".join(lines) + "\n\n"


def _format_namelist_value(value: Any) -> str:
    if isinstance(value, bool):
        return "T" if value else "F"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return ", ".join(_format_namelist_value(item) for item in value)
    return str(value)


def _render_bctides_template(n_open_boundaries: int = 0) -> str:
    if n_open_boundaries < 0:
        raise ValueError("n_open_boundaries must be non-negative")
    lines = [
        "0.0   ! start_time",
        "0 40.0   ! ntip tip_dp",
        "0   ! nbfr",
        f"{n_open_boundaries}   ! nope (open boundary segments from hgrid.gr3)",
    ]
    for i in range(n_open_boundaries):
        lines.append(
            f"! open boundary {i + 1}: TODO set SCHISM elevation/velocity/tracer flags and time series"
        )
    return "\n".join(lines) + "\n"


def write_schism_type1_boundary_forcing(
    forcing: Any,
    work_dir: str | Path,
    *,
    hgrid_path: str | Path | None = None,
    boundary_node_counts: list[int] | tuple[int, ...] | None = None,
    stage_reference_m: float = 0.0,
    end_time_seconds: float | None = None,
) -> SCHISMBoundaryForcingPackage:
    """Write SCHISM Type-1 ``bctides.in`` plus ``elev.th``/``flux.th`` files.

    The input table must have one row per ``boundary_id`` and ``time_seconds``.
    Boundaries with ``boundary_condition_hint=stage`` or a role containing
    ``stage`` become ``iettype=1`` and are written to ``elev.th``. Boundaries
    with ``boundary_condition_hint=flow`` or a role containing ``inflow`` become
    ``ifltype=1`` and are written to ``flux.th`` using SCHISM's convention that
    negative discharge is inflow.
    """

    import pandas as pd

    if isinstance(forcing, str | Path):
        frame = pd.read_csv(forcing)
    else:
        frame = forcing.copy()
    required = {"boundary_id", "time_seconds", "stage_m", "discharge_m3s"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"forcing missing columns: {sorted(missing)}")

    boundary_ids = sorted(int(v) for v in frame["boundary_id"].dropna().unique())
    if boundary_ids != list(range(1, len(boundary_ids) + 1)):
        raise ValueError("boundary_id values must be consecutive and 1-based")

    if boundary_node_counts is None:
        if hgrid_path is None:
            raise ValueError("boundary_node_counts or hgrid_path is required")
        boundary_node_counts = _read_hgrid_open_boundary_node_counts(Path(hgrid_path))
    node_counts = [int(v) for v in boundary_node_counts]
    if len(node_counts) != len(boundary_ids):
        raise ValueError(
            "boundary_node_counts length does not match forcing boundary count: "
            f"{len(node_counts)} != {len(boundary_ids)}"
        )

    metadata = _schism_boundary_metadata(frame, boundary_ids, node_counts)
    time_values = sorted(float(v) for v in frame["time_seconds"].dropna().unique())
    _validate_forcing_grid(frame, boundary_ids, time_values)
    if end_time_seconds is not None:
        end_time = float(end_time_seconds)
        if time_values and end_time > time_values[-1]:
            time_values.append(end_time)

    out_dir = Path(work_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    elev_path = out_dir / "elev.th" if any(row["iettype"] == 1 for row in metadata) else None
    flux_path = out_dir / "flux.th" if any(row["ifltype"] == 1 for row in metadata) else None
    if elev_path is not None:
        _write_schism_th_file(
            frame,
            elev_path,
            time_values,
            [int(row["boundary_id"]) for row in metadata if row["iettype"] == 1],
            "stage_m",
            transform=lambda value: float(value) - float(stage_reference_m),
        )
    if flux_path is not None:
        _write_schism_th_file(
            frame,
            flux_path,
            time_values,
            [int(row["boundary_id"]) for row in metadata if row["ifltype"] == 1],
            "discharge_m3s",
            transform=lambda value: -abs(float(value)),
        )

    bctides_path = out_dir / "bctides.in"
    bctides_path.write_text(_render_bctides_type1(metadata), encoding="utf-8")
    flags_path = out_dir / "open_boundary_flags.csv"
    pd.DataFrame(metadata).to_csv(flags_path, index=False)
    manifest_path = out_dir / "schism_boundary_forcing_manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "format": "SCHISM Type-1 boundary forcing",
                "bctides": bctides_path.name,
                "elev_th": elev_path.name if elev_path is not None else None,
                "flux_th": flux_path.name if flux_path is not None else None,
                "flags": flags_path.name,
                "n_boundaries": len(boundary_ids),
                "n_elevation_boundaries": sum(1 for row in metadata if row["iettype"] == 1),
                "n_flux_boundaries": sum(1 for row in metadata if row["ifltype"] == 1),
                "n_times": len(time_values),
                "time_seconds": time_values,
                "stage_reference_m": float(stage_reference_m),
                "conventions": {
                    "elev_th": "SCHISM Type-1 elevation time history, uniform along boundary",
                    "flux_th": "SCHISM Type-1 discharge time history; negative is inflow",
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return SCHISMBoundaryForcingPackage(
        work_dir=out_dir,
        bctides_path=bctides_path,
        flags_path=flags_path,
        manifest_path=manifest_path,
        elev_th_path=elev_path,
        flux_th_path=flux_path,
        n_boundaries=len(boundary_ids),
        n_elevation_boundaries=sum(1 for row in metadata if row["iettype"] == 1),
        n_flux_boundaries=sum(1 for row in metadata if row["ifltype"] == 1),
        n_times=len(time_values),
    )


def _schism_boundary_metadata(
    frame: Any,
    boundary_ids: list[int],
    node_counts: list[int],
) -> list[dict[str, Any]]:
    metadata: list[dict[str, Any]] = []
    elev_col = 1
    flux_col = 1
    for boundary_id, n_nodes in zip(boundary_ids, node_counts, strict=True):
        first = frame[frame["boundary_id"].eq(boundary_id)].iloc[0]
        kind = _infer_schism_type1_kind(first)
        iettype = 1 if kind == "stage" else 0
        ifltype = 1 if kind == "flow" else 0
        metadata.append(
            {
                "boundary_id": boundary_id,
                "n_nodes": n_nodes,
                "role": str(first["role"]) if "role" in frame.columns else "",
                "boundary_condition_hint": str(first["boundary_condition_hint"])
                if "boundary_condition_hint" in frame.columns
                else kind,
                "iettype": iettype,
                "ifltype": ifltype,
                "itetype": 0,
                "isatype": 0,
                "elev_th_column": elev_col if iettype == 1 else None,
                "flux_th_column": flux_col if ifltype == 1 else None,
            }
        )
        if iettype == 1:
            elev_col += 1
        if ifltype == 1:
            flux_col += 1
    return metadata


def _infer_schism_type1_kind(row: Any) -> str:
    role = str(row.get("role", "")).lower()
    hint = str(row.get("boundary_condition_hint", "")).lower()
    if "stage" in hint or "stage" in role:
        return "stage"
    if "flow" in hint or "inflow" in role:
        return "flow"
    raise ValueError(
        "cannot infer SCHISM Type-1 boundary kind; provide role or boundary_condition_hint"
    )


def _validate_forcing_grid(frame: Any, boundary_ids: list[int], time_values: list[float]) -> None:
    duplicates = frame.duplicated(subset=["boundary_id", "time_seconds"])
    if bool(duplicates.any()):
        raise ValueError("forcing has duplicate boundary_id/time_seconds rows")
    expected = {
        (boundary_id, time_value) for boundary_id in boundary_ids for time_value in time_values
    }
    actual = {
        (int(row.boundary_id), float(row.time_seconds))
        for row in frame[["boundary_id", "time_seconds"]].itertuples(index=False)
    }
    missing = expected - actual
    if missing:
        preview = sorted(missing)[:5]
        raise ValueError(f"forcing missing boundary/time rows: {preview}")


def _write_schism_th_file(
    frame: Any,
    path: Path,
    time_values: list[float],
    boundary_ids: list[int],
    value_column: str,
    *,
    transform: Any,
) -> None:
    rows: list[str] = []
    for time_value in time_values:
        values: list[str] = [f"{time_value:.6f}"]
        for boundary_id in boundary_ids:
            value = _lookup_forcing_value(frame, boundary_id, time_value, value_column)
            values.append(f"{transform(value):.10g}")
        rows.append(" ".join(values))
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")


def _lookup_forcing_value(
    frame: Any, boundary_id: int, time_value: float, value_column: str
) -> Any:
    boundary_frame = frame[frame["boundary_id"].eq(boundary_id)].sort_values("time_seconds")
    exact = boundary_frame[boundary_frame["time_seconds"].eq(time_value)]
    if not exact.empty:
        return exact.iloc[0][value_column]
    previous = boundary_frame[boundary_frame["time_seconds"].le(time_value)]
    if not previous.empty:
        return previous.iloc[-1][value_column]
    return boundary_frame.iloc[0][value_column]


def _render_bctides_type1(metadata: list[dict[str, Any]]) -> str:
    lines = [
        "0.0 ! start_time",
        "0 40.0 ! ntip tip_dp",
        "0 ! nbfr",
        f"{len(metadata)} ! nope",
    ]
    for row in metadata:
        suffix = (
            f"! open boundary {row['boundary_id']} role={row['role']} "
            f"elev_col={row['elev_th_column']} flux_col={row['flux_th_column']}"
        )
        lines.append(
            f"{row['n_nodes']} {row['iettype']} {row['ifltype']} "
            f"{row['itetype']} {row['isatype']} {suffix}"
        )
    return "\n".join(lines) + "\n"


def _read_hgrid_open_boundary_node_counts(hgrid_path: Path) -> list[int]:
    lines = hgrid_path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 2:
        raise ValueError(f"{hgrid_path} is too short to be a SCHISM hgrid.gr3")
    try:
        ne, np_count = (int(v) for v in lines[1].split()[:2])
    except ValueError as exc:
        raise ValueError(f"{hgrid_path} has an invalid element/node count line") from exc
    cursor = 2 + np_count + ne
    if cursor >= len(lines):
        return []
    try:
        n_open = int(lines[cursor].split()[0])
    except ValueError as exc:
        raise ValueError(f"{hgrid_path} has an invalid open-boundary count line") from exc
    cursor += 2
    counts: list[int] = []
    for _ in range(n_open):
        if cursor >= len(lines):
            raise ValueError(f"{hgrid_path} ended inside the open-boundary block")
        try:
            n_nodes = int(lines[cursor].split()[0])
        except ValueError as exc:
            raise ValueError(f"{hgrid_path} has an invalid open-boundary node count") from exc
        counts.append(n_nodes)
        cursor += 1 + n_nodes
    return counts


def read_schism_hydraulic_results(
    work_dir: str | Path,
    *,
    time_index: int | None = None,
    h0: float = 0.01,
) -> SCHISMHydraulicResults:
    """Read SCHISM NetCDF outputs into normalized depth/velocity tables.

    Supports both newer scribed outputs (``outputs/out2d_*.nc`` with optional
    velocity companion files) and old/combined ``schout_*.nc`` outputs.
    """

    source_files = _find_schism_output_files(Path(work_dir))
    ds = _open_schism_output_dataset(source_files)
    dataset, table, selected_idx, warnings = _normalize_schism_hydraulics(
        ds,
        source_files=source_files,
        time_index=time_index,
        h0=h0,
    )
    return SCHISMHydraulicResults(
        dataset=dataset,
        table=table,
        source_files=tuple(source_files),
        n_nodes=int(dataset.sizes["node"]),
        n_times=int(dataset.sizes["time"]),
        selected_time_index=selected_idx,
        warnings=tuple(warnings),
    )


def write_schism_hydraulic_cells_csv(
    results: SCHISMHydraulicResults,
    path: str | Path,
) -> Path:
    """Write normalized SCHISM results as an IBM-compatible hydraulic cell CSV."""

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    results.table.to_csv(out, index=False)
    return out


def _find_schism_output_files(work_dir: Path) -> list[Path]:
    roots = [work_dir / "outputs", work_dir]
    patterns = (
        "out2d_*.nc",
        "schout_*.nc",
        "horizontalVelX_*.nc",
        "horizontalVelY_*.nc",
        "depthAverageVelX_*.nc",
        "depthAverageVelY_*.nc",
        "dahv_*.nc",
        "dahv*.nc",
    )
    seen: set[Path] = set()
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for pattern in patterns:
            for path in sorted(root.glob(pattern)):
                resolved = path.resolve()
                if resolved not in seen:
                    seen.add(resolved)
                    files.append(path)
    if not files:
        raise FileNotFoundError(
            f"No schout_*.nc or out2d_*.nc SCHISM outputs found in {work_dir}; "
            "was the run successful and was outputs/ created?"
        )
    return files


def _open_schism_output_dataset(paths: list[Path]) -> Any:
    import xarray as xr

    datasets = []
    for path in paths:
        ds = xr.open_dataset(path)
        try:
            datasets.append(ds.load())
        finally:
            ds.close()
    if len(datasets) == 1:
        return datasets[0]
    try:
        return xr.combine_by_coords(
            datasets,
            combine_attrs="override",
            compat="override",
            coords="minimal",
            data_vars="minimal",
        )
    except Exception:
        return xr.merge(datasets, compat="override", combine_attrs="override")


def _normalize_schism_hydraulics(
    ds: Any,
    *,
    source_files: list[Path],
    time_index: int | None,
    h0: float,
) -> tuple[Any, Any, int | None, list[str]]:
    import numpy as np
    import pandas as pd
    import xarray as xr

    warnings: list[str] = []
    x_name = _find_schism_var(
        ds,
        exact=("SCHISM_hgrid_node_x", "mesh2d_node_x", "node_x", "x"),
        contains=("hgridnodex", "nodex"),
    )
    y_name = _find_schism_var(
        ds,
        exact=("SCHISM_hgrid_node_y", "mesh2d_node_y", "node_y", "y"),
        contains=("hgridnodey", "nodey"),
    )
    if x_name is None or y_name is None:
        raise ValueError("SCHISM output missing node x/y coordinates")
    x = np.asarray(ds[x_name].values, dtype=float).reshape(-1)
    y = np.asarray(ds[y_name].values, dtype=float).reshape(-1)
    if x.size != y.size:
        raise ValueError(f"SCHISM node x/y length mismatch: {x.size} vs {y.size}")
    n_nodes = int(x.size)

    bathymetry_name = _find_schism_var(
        ds,
        exact=(
            "SCHISM_hgrid_node_depth",
            "schism_bathymetric_depth",
            "bathymetric_depth",
            "depth",
            "depths",
            "hgrid_depth",
        ),
        contains=("hgridnodedepth", "bathymetricdepth"),
    )
    if bathymetry_name is None:
        bathymetric_depth = np.zeros(n_nodes, dtype=float)
        warnings.append("No SCHISM bathymetric depth variable detected; using zero depth.")
    else:
        bathymetry_values, _time_values, _time_dim = _as_time_node(ds[bathymetry_name], n_nodes)
        bathymetric_depth = np.asarray(bathymetry_values[0], dtype=float).reshape(-1)
        if bathymetric_depth.size != n_nodes:
            raise ValueError(f"{bathymetry_name} is not node-aligned")

    elevation_name = _find_schism_var(
        ds,
        exact=("elevation", "elev", "eta", "water_surface_m", "water_surface"),
        contains=("surfaceelevation",),
    )
    depth_name = _find_schism_var(
        ds,
        exact=("water_depth", "waterdepth", "total_depth", "depth_m"),
        contains=("waterdepth", "totaldepth"),
    )
    first_state_name = elevation_name or depth_name
    if first_state_name is None:
        raise ValueError("SCHISM output missing elevation or water-depth variable")
    sample_state, all_time_values, _time_dim = _as_time_node(ds[first_state_name], n_nodes)
    if sample_state.shape[0] == 0:
        raise ValueError(
            "SCHISM output files contain zero time records; check schism.log and "
            "outputs/fatal.error for a solver abort before first output."
        )
    selected_positions, selected_idx = _selected_time_positions(sample_state.shape[0], time_index)
    time_values = all_time_values[selected_positions]

    if elevation_name is not None:
        elevation_all, _time_values, _time_dim = _as_time_node(ds[elevation_name], n_nodes)
        elevation = elevation_all[selected_positions, :]
        total_depth = bathymetric_depth.reshape(1, -1) + elevation
    else:
        elevation = np.full((len(selected_positions), n_nodes), np.nan, dtype=float)
        depth_all, _time_values, _time_dim = _as_time_node(ds[depth_name], n_nodes)  # type: ignore[index]
        total_depth = depth_all[selected_positions, :]

    depth = np.where(total_depth >= float(h0), total_depth, np.nan)
    vx, vy, velocity_warnings = _schism_velocity_components(ds, n_nodes, selected_positions)
    warnings.extend(velocity_warnings)
    if vx is None or vy is None:
        velocity = np.full_like(depth, np.nan)
        vx = np.full_like(depth, np.nan)
        vy = np.full_like(depth, np.nan)
    else:
        velocity = np.sqrt(vx**2 + vy**2)
        velocity = np.where(np.isfinite(depth), velocity, np.nan)
        vx = np.where(np.isfinite(depth), vx, np.nan)
        vy = np.where(np.isfinite(depth), vy, np.nan)

    face_nodes = _schism_face_nodes(ds, n_nodes)
    if face_nodes is None:
        area = np.full(n_nodes, np.nan, dtype=float)
        warnings.append("No SCHISM face connectivity found; area_m2 is NaN.")
    else:
        area = _nodal_tributary_area(x, y, face_nodes)

    normalized = xr.Dataset(
        data_vars={
            "node_x": (("node",), x, {"units": "m"}),
            "node_y": (("node",), y, {"units": "m"}),
            "bathymetric_depth_m": (("node",), bathymetric_depth, {"positive": "down"}),
            "area_m2": (("node",), area),
            "water_surface_m": (("time", "node"), elevation),
            "depth_m": (("time", "node"), depth),
            "velocity_x_ms": (("time", "node"), vx),
            "velocity_y_ms": (("time", "node"), vy),
            "velocity_ms": (("time", "node"), velocity),
        },
        coords={
            "time": np.arange(len(selected_positions), dtype=int),
            "node": np.arange(n_nodes, dtype=int),
            "source_time_index": (("time",), selected_positions.astype(int)),
            "time_seconds": (("time",), time_values.astype(float)),
        },
        attrs={
            "source": "SCHISM NetCDF outputs normalized by OpenLimno",
            "source_files": [str(path) for path in source_files],
            "h0_m": float(h0),
            "bathymetry_source": bathymetry_name or "zeros",
            "elevation_source": elevation_name,
        },
    )
    rows: list[pd.DataFrame] = []
    base = pd.DataFrame(
        {
            "node_id": np.arange(1, n_nodes + 1, dtype=int),
            "cell_id": [f"schism_node_{i:06d}" for i in range(1, n_nodes + 1)],
            "x": x,
            "y": y,
            "center_x_m": x,
            "center_y_m": y,
            "bathymetric_depth_m": bathymetric_depth,
            "area_m2": area,
        }
    )
    for local_time, source_time in enumerate(selected_positions.astype(int)):
        frame = base.copy()
        frame["time_index"] = int(local_time)
        frame["source_time_index"] = int(source_time)
        frame["time_seconds"] = float(time_values[local_time])
        frame["water_surface_m"] = elevation[local_time]
        frame["depth_m"] = depth[local_time]
        frame["velocity_x_ms"] = vx[local_time]
        frame["velocity_y_ms"] = vy[local_time]
        frame["velocity_ms"] = velocity[local_time]
        frame["hydraulic_source"] = "schism"
        rows.append(frame)
    table = pd.concat(rows, ignore_index=True)
    table.attrs["openlimno_source_model"] = "SCHISM"
    table.attrs["openlimno_output_table"] = "hydraulic_cells"
    return normalized, table, selected_idx, warnings


def _find_schism_var(
    ds: Any,
    *,
    exact: tuple[str, ...],
    contains: tuple[str, ...] = (),
) -> str | None:
    norm_exact = {_norm_schism_name(name) for name in exact}
    for name in ds.variables:
        if _norm_schism_name(str(name)) in norm_exact:
            return str(name)
    norm_contains = tuple(_norm_schism_name(name) for name in contains)
    for name in ds.variables:
        norm = _norm_schism_name(str(name))
        if any(token in norm for token in norm_contains):
            return str(name)
    return None


def _norm_schism_name(name: str) -> str:
    return "".join(ch.lower() for ch in name if ch.isalnum())


def _as_time_node(da: Any, n_nodes: int) -> tuple[Any, Any, str | None]:
    import numpy as np

    dims = list(da.dims)
    time_axis = next(
        (
            i
            for i, dim in enumerate(dims)
            if "time" in _norm_schism_name(str(dim))
            or np.issubdtype(getattr(da.coords.get(dim), "dtype", object), np.datetime64)
        ),
        None,
    )
    time_dim = str(dims[time_axis]) if time_axis is not None else None
    node_axis = next(
        (
            i
            for i, dim in enumerate(dims)
            if da.sizes[dim] == n_nodes and i != time_axis and "node" in _norm_schism_name(str(dim))
        ),
        None,
    )
    if node_axis is None:
        node_axis = next(
            (i for i, dim in enumerate(dims) if da.sizes[dim] == n_nodes and i != time_axis),
            None,
        )
    if node_axis is None:
        raise ValueError(f"{da.name!r} is not node-aligned with {n_nodes} nodes")
    node_dim = str(dims[node_axis])
    extra_dims = [str(dim) for dim in dims if str(dim) not in {time_dim, node_dim}]
    if time_axis is None:
        ordered = da.transpose(node_dim, *extra_dims)
        values = np.expand_dims(np.asarray(ordered.values, dtype=float), axis=0)
        time_values = np.array([0.0], dtype=float)
        return _collapse_extra_axes(values), time_values, None

    ordered = da.transpose(time_dim, node_dim, *extra_dims)
    values = _collapse_extra_axes(np.asarray(ordered.values, dtype=float))
    coord = da.coords.get(time_dim)
    if coord is not None:
        raw_time = np.asarray(coord.values)
        if np.issubdtype(raw_time.dtype, np.datetime64):
            time_values = ((raw_time - raw_time[0]) / np.timedelta64(1, "s")).astype(float)
        else:
            time_values = raw_time.astype(float)
    else:
        time_values = np.arange(values.shape[0], dtype=float)
    return values, time_values, time_dim


def _collapse_extra_axes(values: Any) -> Any:
    import numpy as np

    while values.ndim > 2:
        finite = np.isfinite(values)
        counts = np.sum(finite, axis=2)
        sums = np.nansum(values, axis=2)
        values = np.divide(
            sums,
            counts,
            out=np.full_like(sums, np.nan, dtype=float),
            where=counts > 0,
        )
    return values


def _selected_time_positions(n_times: int, time_index: int | None) -> tuple[Any, int | None]:
    import numpy as np

    if time_index is None:
        return np.arange(n_times, dtype=int), None
    idx = int(time_index)
    if idx < 0:
        idx = n_times + idx
    if idx < 0 or idx >= n_times:
        raise IndexError(f"time_index out of range: {time_index} for {n_times} time steps")
    return np.asarray([idx], dtype=int), idx


def _schism_velocity_components(
    ds: Any,
    n_nodes: int,
    selected_positions: Any,
) -> tuple[Any | None, Any | None, list[str]]:
    warnings: list[str] = []
    ux_name = _find_schism_var(
        ds,
        exact=("depthAverageVelX", "horizontalVelX", "velocity_x", "u", "uvel", "dahv_x"),
        contains=("velocityx", "velx"),
    )
    uy_name = _find_schism_var(
        ds,
        exact=("depthAverageVelY", "horizontalVelY", "velocity_y", "v", "vvel", "dahv_y"),
        contains=("velocityy", "vely"),
    )
    if ux_name is not None and uy_name is not None:
        ux, _time_values, _time_dim = _as_time_node(ds[ux_name], n_nodes)
        uy, _time_values, _time_dim = _as_time_node(ds[uy_name], n_nodes)
        return ux[selected_positions, :], uy[selected_positions, :], warnings

    vector_name = _find_schism_var(
        ds,
        exact=("hvel", "dahv", "depthAverageVel", "horizontalVel"),
        contains=("horizontalvel", "depthaveragevel"),
    )
    if vector_name is None:
        warnings.append("No SCHISM velocity component variables detected.")
        return None, None, warnings
    da = ds[vector_name]
    component_dim = next(
        (
            dim
            for dim in da.dims
            if da.sizes[dim] == 2
            and "time" not in _norm_schism_name(str(dim))
            and "node" not in _norm_schism_name(str(dim))
        ),
        None,
    )
    if component_dim is None:
        warnings.append(f"Velocity vector {vector_name!r} has no 2-component dimension.")
        return None, None, warnings
    ux, _time_values, _time_dim = _as_time_node(da.isel({component_dim: 0}), n_nodes)
    uy, _time_values, _time_dim = _as_time_node(da.isel({component_dim: 1}), n_nodes)
    return ux[selected_positions, :], uy[selected_positions, :], warnings


def _schism_face_nodes(ds: Any, n_nodes: int) -> Any | None:
    import numpy as np

    face_name = _find_schism_var(
        ds,
        exact=(
            "SCHISM_hgrid_face_nodes",
            "mesh2d_face_nodes",
            "face_nodes",
            "element_nodes",
            "ele",
        ),
        contains=("facenodes", "elementnodes"),
    )
    if face_name is None:
        return None
    arr = np.asarray(ds[face_name].values)
    while arr.ndim > 2:
        arr = arr[0]
    if arr.ndim != 2:
        return None
    fill = ds[face_name].attrs.get("_FillValue", -1)
    start_index = int(ds[face_name].attrs.get("start_index", 0))
    out = []
    for row in arr:
        nodes = []
        for raw in row:
            if not np.isfinite(float(raw)):
                continue
            node = int(raw)
            if node == int(fill) or node < 0:
                continue
            if start_index == 1 or node >= n_nodes:
                node -= 1
            nodes.append(node)
        if len(nodes) >= 3:
            out.append(nodes)
    return out


def _nodal_tributary_area(x: Any, y: Any, face_nodes: list[list[int]]) -> Any:
    import numpy as np

    area = np.zeros(len(x), dtype=float)
    for nodes in face_nodes:
        xs = np.asarray([x[i] for i in nodes], dtype=float)
        ys = np.asarray([y[i] for i in nodes], dtype=float)
        polygon_area = 0.5 * abs(float(np.dot(xs, np.roll(ys, -1)) - np.dot(ys, np.roll(xs, -1))))
        share = polygon_area / len(nodes)
        for node in nodes:
            area[node] += share
    return area


def _write_hgrid_from_ugrid(ugrid_path: Path, hgrid_path: Path) -> dict[str, Any]:
    """Convert a UGRID-2D NetCDF mesh into a SCHISM hgrid.gr3 ASCII file.

    SCHISM's hgrid.gr3 format:

        line 1:  mesh name (free text)
        line 2:  ne np                      (n elements, n nodes)
        next np lines:  i x y z             (1-indexed nodes)
        next ne lines:  i type n1 n2 n3 [n4]
        boundary blocks are written when UGRID boundary connectivity variables
        are present.

    UGRID conventions: ``mesh2d_face_nodes`` with fill_value indicating
    "not a node" (typically -1 or NetCDF _FillValue).
    """
    import numpy as np
    import xarray as xr

    ds = xr.open_dataset(ugrid_path)
    try:
        # Try common UGRID variable names
        x_name = next((n for n in ("mesh2d_node_x", "node_x") if n in ds.variables), None)
        y_name = next((n for n in ("mesh2d_node_y", "node_y") if n in ds.variables), None)
        face_name = next(
            (n for n in ("mesh2d_face_nodes", "face_nodes") if n in ds.variables),
            None,
        )
        if x_name is None or y_name is None or face_name is None:
            raise ValueError("UGRID mesh missing required vars (mesh2d_node_x/y/face_nodes)")
        x = np.asarray(ds[x_name].values, dtype=float)
        y = np.asarray(ds[y_name].values, dtype=float)
        face_nodes = np.asarray(ds[face_name].values)

        # Bottom elevation (z): try several CF names; default 0
        z_name = next(
            (
                n
                for n in (
                    "schism_bathymetric_depth",
                    "bathymetric_depth",
                    "depth",
                    "bottom_elevation",
                    "node_z",
                )
                if n in ds.variables
            ),
            None,
        )
        z = np.asarray(ds[z_name].values, dtype=float) if z_name else np.zeros_like(x)
        depth_reference = (
            float(ds.attrs["schism_depth_reference_m"])
            if "schism_depth_reference_m" in ds.attrs
            else None
        )

        open_boundaries = _read_boundary_connectivity(
            ds,
            (
                "open_boundary_node_connectivity",
                "open_boundary_nodes",
                "mesh2d_open_boundary_nodes",
            ),
        )
        land_boundaries = _read_boundary_connectivity(
            ds,
            (
                "land_boundary_node_connectivity",
                "land_boundary_nodes",
                "mesh2d_land_boundary_nodes",
            ),
        )

        # Detect fill value in face_nodes
        fill = ds[face_name].attrs.get("_FillValue", -1)
        np_count = len(x)
        hgrid_faces = _schism_hgrid_faces(face_nodes, fill=fill, x=x, y=y)
        ne = len(hgrid_faces)
    finally:
        ds.close()

    # Write
    with hgrid_path.open("w", encoding="utf-8") as f:
        f.write("OpenLimno UGRID-derived mesh\n")
        f.write(f"{ne} {np_count}\n")
        for i in range(np_count):
            f.write(f"{i + 1} {x[i]:.6f} {y[i]:.6f} {z[i]:.6f}\n")
        for i, nodes in enumerate(hgrid_faces):
            valid = [int(n) + 1 for n in nodes]
            t = len(valid)  # 3 = tri, 4 = quad
            f.write(f"{i + 1} {t} " + " ".join(str(n) for n in valid) + "\n")
        _write_boundary_block(f, open_boundaries, kind="open")
        _write_boundary_block(f, land_boundaries, kind="land")
    return {
        "n_open_boundaries": len(open_boundaries),
        "n_open_boundary_nodes": sum(len(nodes) for nodes in open_boundaries),
        "n_land_boundaries": len(land_boundaries),
        "n_land_boundary_nodes": sum(len(nodes) for nodes in land_boundaries),
        "depth_source": z_name or "zeros",
        "depth_reference_m": depth_reference,
    }


def _schism_hgrid_faces(face_nodes: Any, *, fill: Any, x: Any, y: Any) -> list[list[int]]:
    """Return SCHISM-safe face nodes from UGRID connectivity.

    HEC-RAS cutline quads can become concave or inverted where surveyed
    cross-sections bend or overlap. SCHISM aborts on negative element areas, so
    quads are split into oriented triangles for solver handoff.
    """
    import numpy as np

    faces: list[list[int]] = []
    for row in np.asarray(face_nodes):
        nodes: list[int] = []
        for raw in row:
            value = float(raw)
            if not np.isfinite(value):
                continue
            node = int(raw)
            if node == int(fill) or node < 0:
                continue
            nodes.append(node)
        if len(nodes) == 3:
            faces.append(_orient_triangle_ccw(nodes, x=x, y=y))
        elif len(nodes) == 4:
            faces.extend(_triangulate_quad(nodes, x=x, y=y))
        elif len(nodes) > 4:
            anchor = nodes[0]
            for i in range(1, len(nodes) - 1):
                faces.append(_orient_triangle_ccw([anchor, nodes[i], nodes[i + 1]], x=x, y=y))
    return faces


def _write_constant_gr3_from_hgrid(
    hgrid_path: Path,
    out_path: Path,
    *,
    value: float,
    title: str,
) -> None:
    lines = hgrid_path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 2:
        raise ValueError(f"{hgrid_path} is too short to derive {out_path.name}")
    ne, np_count = (int(v) for v in lines[1].split()[:2])
    node_lines = lines[2 : 2 + np_count]
    out: list[str] = [title, f"{ne} {np_count}"]
    for line in node_lines:
        parts = line.split()
        if len(parts) < 3:
            raise ValueError(f"{hgrid_path} has an invalid node line: {line!r}")
        out.append(f"{parts[0]} {parts[1]} {parts[2]} {float(value):.8g}")
    out_path.write_text("\n".join(out) + "\n", encoding="utf-8")


def _triangulate_quad(nodes: list[int], *, x: Any, y: Any) -> list[list[int]]:
    a, b, c, d = nodes
    candidates = (
        ([a, b, c], [a, c, d]),
        ([a, b, d], [b, c, d]),
    )
    best = max(
        candidates,
        key=lambda pair: min(abs(_triangle_area2(tri, x=x, y=y)) for tri in pair),
    )
    return [_orient_triangle_ccw(list(tri), x=x, y=y) for tri in best]


def _orient_triangle_ccw(nodes: list[int], *, x: Any, y: Any) -> list[int]:
    if _triangle_area2(nodes, x=x, y=y) < 0.0:
        return [nodes[0], nodes[2], nodes[1]]
    return nodes


def _triangle_area2(nodes: list[int], *, x: Any, y: Any) -> float:
    a, b, c = nodes
    return float((x[b] - x[a]) * (y[c] - y[a]) - (y[b] - y[a]) * (x[c] - x[a]))


def _read_boundary_connectivity(ds: Any, names: tuple[str, ...]) -> list[list[int]]:
    """Read optional UGRID boundary connectivity arrays as 1-indexed SCHISM nodes."""

    import numpy as np

    name = next((candidate for candidate in names if candidate in ds.variables), None)
    if name is None:
        return []
    arr = ds[name]
    values = np.asarray(arr.values)
    fill = arr.attrs.get("_FillValue", -1)
    start_index = int(arr.attrs.get("start_index", 0))
    if values.ndim == 1:
        values = values.reshape(1, -1)
    if values.ndim != 2:
        raise ValueError(f"{name} must be 1D or 2D boundary connectivity")
    out: list[list[int]] = []
    for row in values:
        nodes: list[int] = []
        for raw in row:
            if not np.isfinite(float(raw)):
                continue
            node = int(raw)
            if node == int(fill) or node < 0:
                continue
            nodes.append(node - start_index + 1)
        if nodes:
            out.append(nodes)
    return out


def _write_boundary_block(handle: Any, boundaries: list[list[int]], *, kind: str) -> None:
    total = sum(len(nodes) for nodes in boundaries)
    if kind == "open":
        handle.write(f"{len(boundaries)} = number of open boundary segments\n")
        handle.write(f"{total} = total number of open boundary nodes\n")
        for i, nodes in enumerate(boundaries, start=1):
            handle.write(f"{len(nodes)} = number of nodes for open boundary {i}\n")
            for node in nodes:
                handle.write(f"{node}\n")
        return
    handle.write(f"{len(boundaries)} = number of land boundary segments\n")
    handle.write(f"{total} = total number of land boundary nodes\n")
    for i, nodes in enumerate(boundaries, start=1):
        handle.write(f"{len(nodes)} 0 = number of nodes for land boundary {i}\n")
        for node in nodes:
            handle.write(f"{node}\n")


__all__ = [
    "LTS_VERSION",
    "SCHISMAdapter",
    "SCHISMBoundaryForcingPackage",
    "SCHISMHydraulicResults",
    "SCHISMRunReport",
    "read_schism_hydraulic_results",
    "write_schism_hydraulic_cells_csv",
    "write_schism_type1_boundary_forcing",
]
