"""Native individual-based population model.

This package is OpenLimno's non-NetLogo path for inSTREAM-style workflows.
It does not depend on NetLogo and is designed to consume OpenLimno habitat-cell
tables directly.
"""

from .acceptance import (
    IBMAcceptanceItem,
    build_ibm_acceptance_report,
    write_ibm_acceptance_report,
)
from .events import (
    daily_event_summary,
    summarize_events,
    write_event_report,
)
from .experiments import (
    IBMCalibrationResult,
    IBMEnsembleResult,
    parse_parameter_grid,
    run_ibm_abc_calibration,
    run_ibm_calibration,
    run_ibm_ensemble,
)
from .instream7 import (
    Instream7BenchmarkResult,
    Instream7Case,
    Instream7NetLogoReferenceResult,
    Instream7Reach,
    build_population_from_official_adult_arrivals,
    build_population_from_official_initial,
    compare_instream7_native_to_brief,
    discover_instream7_cases,
    extract_instream7_archive,
    parse_instream7_case,
    prepare_instream7_netlogo_reference_case,
    read_instream7_brief_population,
    read_official_adult_arrivals,
    read_official_initial_population,
    read_official_time_series,
    run_instream7_netlogo_reference,
    run_instream7_official_benchmark,
    species_profile_from_official_case,
    summarize_instream7_brief_population,
    summarize_instream7_parity,
    write_instream7_netlogo_setup_file,
    write_instream7_parity_report,
)
from .native import (
    NativeIBMConfig,
    NativeIBMResult,
    SpeciesProfile,
    build_initial_population,
    run_native_ibm,
    write_native_ibm_result,
)
from .runtime_submodels import (
    BioenergeticGrowthModel,
    CalibratedReddPlacementModel,
    CrossReachMovementModel,
    GrowthRiskHabitatModel,
    NetworkMovementModel,
    ReddRecruitmentModel,
    SizePriorityCellChooser,
)
from .scenario import (
    IBM_SCHEMA_VERSION,
    load_ibm_scenario,
    load_ibm_schema,
    load_species_profile,
    run_ibm_scenario,
    validate_ibm_scenario,
    validate_species_profile,
    write_species_profile,
)
from .studio import (
    compare_instream7_for_studio,
    default_studio_scenario,
    import_gis_for_studio,
    run_ibm_studio,
    run_instream7_benchmark_for_studio,
    run_studio_calibration,
    run_studio_ensemble,
    run_studio_scenario,
    validate_studio_payload,
    write_studio_scenario_files,
)
from .submodels import (
    IBMSubmodel,
    default_submodel_selection,
    list_ibm_submodels,
    resolve_submodel_selection,
    validate_submodel_selection,
)

__all__ = [
    "IBM_SCHEMA_VERSION",
    "BioenergeticGrowthModel",
    "CalibratedReddPlacementModel",
    "CrossReachMovementModel",
    "GrowthRiskHabitatModel",
    "IBMAcceptanceItem",
    "IBMCalibrationResult",
    "IBMEnsembleResult",
    "IBMSubmodel",
    "Instream7BenchmarkResult",
    "Instream7Case",
    "Instream7NetLogoReferenceResult",
    "Instream7Reach",
    "NativeIBMConfig",
    "NativeIBMResult",
    "NetworkMovementModel",
    "ReddRecruitmentModel",
    "SizePriorityCellChooser",
    "SpeciesProfile",
    "build_ibm_acceptance_report",
    "build_initial_population",
    "build_population_from_official_adult_arrivals",
    "build_population_from_official_initial",
    "compare_instream7_for_studio",
    "compare_instream7_native_to_brief",
    "daily_event_summary",
    "default_studio_scenario",
    "default_submodel_selection",
    "discover_instream7_cases",
    "extract_instream7_archive",
    "import_gis_for_studio",
    "list_ibm_submodels",
    "load_ibm_scenario",
    "load_ibm_schema",
    "load_species_profile",
    "parse_instream7_case",
    "parse_parameter_grid",
    "prepare_instream7_netlogo_reference_case",
    "read_instream7_brief_population",
    "read_official_adult_arrivals",
    "read_official_initial_population",
    "read_official_time_series",
    "resolve_submodel_selection",
    "run_ibm_abc_calibration",
    "run_ibm_calibration",
    "run_ibm_ensemble",
    "run_ibm_scenario",
    "run_ibm_studio",
    "run_instream7_benchmark_for_studio",
    "run_instream7_netlogo_reference",
    "run_instream7_official_benchmark",
    "run_native_ibm",
    "run_studio_calibration",
    "run_studio_ensemble",
    "run_studio_scenario",
    "species_profile_from_official_case",
    "summarize_events",
    "summarize_instream7_brief_population",
    "summarize_instream7_parity",
    "validate_ibm_scenario",
    "validate_species_profile",
    "validate_studio_payload",
    "validate_submodel_selection",
    "write_event_report",
    "write_ibm_acceptance_report",
    "write_instream7_netlogo_setup_file",
    "write_instream7_parity_report",
    "write_native_ibm_result",
    "write_species_profile",
    "write_studio_scenario_files",
]
