"""inSTREAM 7 brief-population parsing + native-vs-reference parity reporting.

Extracted from openlimno.ibm.instream7 as part of
R-IBM-GOD-OBJECT (ADR-0016) deeper split: brief-format parsing and
parity comparison are conceptually separate from inSTREAM case parsing,
NetLogo reference running, and the official benchmark runner.

Public functions:
  - ``read_instream7_brief_population`` — load BriefPopOut CSV emitted by NetLogo
  - ``summarize_instream7_brief_population`` — daily / phase aggregation
  - ``compare_instream7_native_to_brief`` — native engine vs reference parity
  - ``summarize_instream7_parity`` — single-row pass/fail summary
  - ``write_instream7_parity_report`` — write comparison + summary CSVs

openlimno.ibm.instream7 re-exports all 5 public names so existing
callers (from openlimno.ibm.instream7 import ...) keep working.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


def read_instream7_brief_population(path: str | Path) -> pd.DataFrame:
    """Read an inSTREAM 7 ``BriefPopOut`` CSV generated by NetLogo."""

    df = pd.read_csv(path, skiprows=1)
    rename = {
        "BehavSp-Run": "behaviorspace_run",
        "End of time step": "end_time",
        "IsCensus?": "is_census",
        "Light phase": "light_phase",
        "Reach": "reach_id",
        "Flow": "flow_m3s",
        "Temperature": "temperature_c",
        "Turbidity": "turbidity_ntu",
        "Species": "species",
        "Age class": "age_class",
        "Count": "count",
        "Mean length": "mean_length_cm",
        "Mean weight": "mean_weight_g",
        "Mean condition": "mean_condition",
        "FractionDriftFeeding": "fraction_drift_feeding",
        "FractionSearchFeeding": "fraction_search_feeding",
        "FractionHiding": "fraction_hiding",
    }
    missing = set(rename) - set(df.columns)
    if missing:
        raise ValueError(f"{path} missing inSTREAM 7 BriefPop columns: {sorted(missing)}")

    out = df.rename(columns=rename)[list(rename.values())].copy()
    out["end_timestamp"] = pd.to_datetime(out["end_time"], errors="coerce")
    out["is_census"] = out["is_census"].astype(str).str.lower().isin({"true", "1", "yes"})
    numeric_cols = [
        "behaviorspace_run",
        "flow_m3s",
        "temperature_c",
        "turbidity_ntu",
        "count",
        "mean_length_cm",
        "mean_weight_g",
        "mean_condition",
        "fraction_drift_feeding",
        "fraction_search_feeding",
        "fraction_hiding",
    ]
    for col in numeric_cols:
        out[col] = pd.to_numeric(out[col], errors="coerce")
    out["count"] = out["count"].fillna(0).astype(int)
    out["mean_length_mm"] = out["mean_length_cm"] * 10.0
    out["biomass_g"] = out["count"] * out["mean_weight_g"]
    return out


def _weighted_mean(values: pd.Series, weights: pd.Series) -> float:
    valid = values.notna() & weights.notna()
    if not bool(valid.any()):
        return float("nan")
    valid_values = values[valid].to_numpy(dtype=float)
    valid_weights = weights[valid].to_numpy(dtype=float)
    total = float(valid_weights.sum())
    if total <= 0.0:
        return float("nan")
    return float(np.average(valid_values, weights=valid_weights))


def summarize_instream7_brief_population(table: pd.DataFrame) -> pd.DataFrame:
    """Aggregate inSTREAM 7 ``BriefPopOut`` rows to native-summary shape."""

    columns = [
        "behaviorspace_run",
        "end_time",
        "end_timestamp",
        "light_phase",
        "is_census",
        "reach_id",
        "species",
        "abundance",
        "biomass_g",
        "mean_length_mm",
        "mean_weight_g",
        "mean_condition",
        "fraction_drift_feeding",
        "fraction_search_feeding",
        "fraction_hiding",
        "flow_m3s",
        "temperature_c",
        "turbidity_ntu",
        "age_classes",
    ]
    if table.empty:
        return pd.DataFrame(columns=columns)

    group_cols = [
        "behaviorspace_run",
        "end_time",
        "end_timestamp",
        "light_phase",
        "is_census",
        "reach_id",
        "species",
        "flow_m3s",
        "temperature_c",
        "turbidity_ntu",
    ]
    rows: list[dict[str, object]] = []
    for keys, group in table.groupby(group_cols, dropna=False, sort=True):
        if not isinstance(keys, tuple):
            keys = (keys,)
        row = dict(zip(group_cols, keys, strict=True))
        weights = group["count"].astype(float)
        row["abundance"] = int(group["count"].sum())
        row["biomass_g"] = float(group["biomass_g"].sum())
        row["mean_length_mm"] = _weighted_mean(group["mean_length_mm"], weights)
        row["mean_weight_g"] = _weighted_mean(group["mean_weight_g"], weights)
        row["mean_condition"] = _weighted_mean(group["mean_condition"], weights)
        row["fraction_drift_feeding"] = _weighted_mean(group["fraction_drift_feeding"], weights)
        row["fraction_search_feeding"] = _weighted_mean(group["fraction_search_feeding"], weights)
        row["fraction_hiding"] = _weighted_mean(group["fraction_hiding"], weights)
        row["age_classes"] = "|".join(sorted(group["age_class"].astype(str).unique()))
        rows.append(row)
    return pd.DataFrame.from_records(rows, columns=columns)


def _brief_sequence(summary: pd.DataFrame) -> pd.DataFrame:
    columns = [
        "netlogo_run",
        "reach_id",
        "species",
        "comparison_day",
        "netlogo_end_time",
        "netlogo_abundance",
        "netlogo_biomass_g",
        "netlogo_mean_length_mm",
    ]
    if summary.empty:
        return pd.DataFrame(columns=columns)

    required = {"reach_id", "species", "abundance", "biomass_g", "mean_length_mm"}
    missing = required - set(summary.columns)
    if missing:
        raise ValueError(f"NetLogo BriefPop summary missing columns: {sorted(missing)}")

    table = summary.copy()
    if "behaviorspace_run" not in table.columns:
        table["behaviorspace_run"] = 1
    if "end_time" not in table.columns:
        table["end_time"] = ""
    if "end_timestamp" not in table.columns:
        table["end_timestamp"] = pd.NaT
    table["end_timestamp"] = pd.to_datetime(table["end_timestamp"], errors="coerce")
    table = table.sort_values(
        ["behaviorspace_run", "reach_id", "species", "end_timestamp", "end_time"],
        kind="mergesort",
    ).reset_index(drop=True)
    table["comparison_day"] = table.groupby(
        ["behaviorspace_run", "reach_id", "species"],
        dropna=False,
    ).cumcount()
    return table.rename(
        columns={
            "behaviorspace_run": "netlogo_run",
            "end_time": "netlogo_end_time",
            "abundance": "netlogo_abundance",
            "biomass_g": "netlogo_biomass_g",
            "mean_length_mm": "netlogo_mean_length_mm",
        }
    )[columns]


def _native_sequence(summary: pd.DataFrame) -> pd.DataFrame:
    columns = [
        "scenario_id",
        "reach_id",
        "species",
        "comparison_day",
        "native_day",
        "native_official_date",
        "native_abundance",
        "native_biomass_g",
        "native_mean_length_mm",
    ]
    if summary.empty:
        return pd.DataFrame(columns=columns)

    required = {"reach_id", "species", "day", "abundance", "biomass_g", "mean_length_mm"}
    missing = required - set(summary.columns)
    if missing:
        raise ValueError(f"native IBM summary missing columns: {sorted(missing)}")

    table = summary.copy()
    if "scenario_id" not in table.columns:
        table["scenario_id"] = ""
    if "official_date" not in table.columns:
        table["official_date"] = ""
    table["day"] = pd.to_numeric(table["day"], errors="coerce")
    table = table.sort_values(
        ["reach_id", "species", "day"],
        kind="mergesort",
    ).reset_index(drop=True)
    fallback = table.groupby(["reach_id", "species"], dropna=False).cumcount()
    table["comparison_day"] = table["day"].fillna(fallback).astype(int)
    return table.rename(
        columns={
            "day": "native_day",
            "official_date": "native_official_date",
            "abundance": "native_abundance",
            "biomass_g": "native_biomass_g",
            "mean_length_mm": "native_mean_length_mm",
        }
    )[columns]


def _relative_delta(native: pd.Series, expected: pd.Series) -> pd.Series:
    delta = native - expected
    denominator = expected.abs()
    values = np.where(
        denominator > 0.0,
        delta / denominator,
        np.where(delta.abs() <= 0.0, 0.0, np.inf),
    )
    return pd.Series(values, index=native.index)


def compare_instream7_native_to_brief(
    native_summary: pd.DataFrame,
    netlogo_brief_summary: pd.DataFrame,
    *,
    abundance_tolerance: int = 0,
    biomass_relative_tolerance: float = 0.05,
    mean_length_tolerance_mm: float = 1.0,
) -> pd.DataFrame:
    # BriefPop lacks a numeric day column, so align by ordered snapshot within
    # each BehaviorSpace run, reach, and species.
    native = _native_sequence(native_summary)
    netlogo = _brief_sequence(netlogo_brief_summary)
    merged = netlogo.merge(
        native,
        on=["reach_id", "species", "comparison_day"],
        how="outer",
        sort=True,
    )
    columns = [
        "netlogo_run",
        "scenario_id",
        "reach_id",
        "species",
        "comparison_day",
        "netlogo_end_time",
        "native_day",
        "native_official_date",
        "netlogo_abundance",
        "native_abundance",
        "abundance_delta_native_minus_netlogo",
        "abundance_abs_delta",
        "netlogo_biomass_g",
        "native_biomass_g",
        "biomass_delta_native_minus_netlogo_g",
        "biomass_relative_delta",
        "netlogo_mean_length_mm",
        "native_mean_length_mm",
        "mean_length_delta_native_minus_netlogo_mm",
        "mean_length_abs_delta_mm",
        "abundance_pass",
        "biomass_pass",
        "mean_length_pass",
        "matched",
        "passed",
        "comparison_note",
    ]
    if merged.empty:
        return pd.DataFrame(columns=columns)

    for col in (
        "netlogo_abundance",
        "native_abundance",
        "netlogo_biomass_g",
        "native_biomass_g",
        "netlogo_mean_length_mm",
        "native_mean_length_mm",
    ):
        merged[col] = pd.to_numeric(merged[col], errors="coerce")

    native_present = merged["native_abundance"].notna()
    netlogo_present = merged["netlogo_abundance"].notna()
    merged["matched"] = native_present & netlogo_present
    merged["abundance_delta_native_minus_netlogo"] = (
        merged["native_abundance"] - merged["netlogo_abundance"]
    )
    merged["abundance_abs_delta"] = merged[
        "abundance_delta_native_minus_netlogo"
    ].abs()
    merged["biomass_delta_native_minus_netlogo_g"] = (
        merged["native_biomass_g"] - merged["netlogo_biomass_g"]
    )
    merged["biomass_relative_delta"] = _relative_delta(
        merged["native_biomass_g"],
        merged["netlogo_biomass_g"],
    )
    merged["mean_length_delta_native_minus_netlogo_mm"] = (
        merged["native_mean_length_mm"] - merged["netlogo_mean_length_mm"]
    )
    merged["mean_length_abs_delta_mm"] = merged[
        "mean_length_delta_native_minus_netlogo_mm"
    ].abs()

    both_mean_length_missing = (
        merged["native_mean_length_mm"].isna()
        & merged["netlogo_mean_length_mm"].isna()
    )
    merged["abundance_pass"] = (
        merged["matched"] & (merged["abundance_abs_delta"] <= abundance_tolerance)
    )
    merged["biomass_pass"] = (
        merged["matched"]
        & (merged["biomass_relative_delta"].abs() <= biomass_relative_tolerance)
    )
    merged["mean_length_pass"] = (
        merged["matched"]
        & (
            (merged["mean_length_abs_delta_mm"] <= mean_length_tolerance_mm)
            | both_mean_length_missing
        )
    )
    merged["passed"] = (
        merged["abundance_pass"] & merged["biomass_pass"] & merged["mean_length_pass"]
    )
    merged["comparison_note"] = np.select(
        [
            ~native_present,
            ~netlogo_present,
            merged["passed"],
        ],
        [
            "missing_native",
            "missing_netlogo",
            "within_tolerance",
        ],
        default="outside_tolerance",
    )
    return merged[columns].sort_values(
        ["netlogo_run", "scenario_id", "reach_id", "species", "comparison_day"],
        kind="mergesort",
        na_position="last",
    ).reset_index(drop=True)


def summarize_instream7_parity(comparison: pd.DataFrame) -> pd.DataFrame:
    """Summarize pass/fail counts from a native-vs-inSTREAM comparison table."""

    columns = [
        "scenario_id",
        "reach_id",
        "species",
        "rows",
        "passed_rows",
        "failed_rows",
        "matched_rows",
        "max_abundance_abs_delta",
        "max_biomass_relative_delta_abs",
        "max_mean_length_abs_delta_mm",
        "passed",
    ]
    if comparison.empty:
        return pd.DataFrame(columns=columns)
    table = comparison.copy()
    table["passed"] = table["passed"].fillna(False).astype(bool)
    table["matched"] = table["matched"].fillna(False).astype(bool)
    table["biomass_relative_delta_abs"] = pd.to_numeric(
        table["biomass_relative_delta"],
        errors="coerce",
    ).abs()
    grouped = table.groupby(["scenario_id", "reach_id", "species"], dropna=False)
    summary = grouped.agg(
        rows=("passed", "size"),
        passed_rows=("passed", "sum"),
        matched_rows=("matched", "sum"),
        max_abundance_abs_delta=("abundance_abs_delta", "max"),
        max_biomass_relative_delta_abs=("biomass_relative_delta_abs", "max"),
        max_mean_length_abs_delta_mm=("mean_length_abs_delta_mm", "max"),
    ).reset_index()
    summary["failed_rows"] = summary["rows"] - summary["passed_rows"]
    summary["passed"] = summary["failed_rows"] == 0
    return summary[columns].sort_values(
        ["scenario_id", "reach_id", "species"],
        kind="mergesort",
    ).reset_index(drop=True)


def write_instream7_parity_report(
    comparison: pd.DataFrame,
    output_path: str | Path,
) -> dict[str, str]:
    """Write detailed and summarized inSTREAM parity reports."""

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    comparison.to_csv(out, index=False)
    summary_path = out.with_name(f"{out.stem}_summary{out.suffix}")
    summarize_instream7_parity(comparison).to_csv(summary_path, index=False)
    return {
        "instream7_parity_detail": str(out),
        "instream7_parity_summary": str(summary_path),
    }


def _column_lookup(columns: pd.Index, name: str) -> str:
    by_norm = {str(col).lower(): str(col) for col in columns}
    found = by_norm.get(name.lower())
    if found is None:
        raise ValueError(f"shapefile missing field {name!r}")
    return found


