#!/usr/bin/env bash
#
# Three-AI code review: runs Codex, Gemini, and Claude Code in parallel
# against the same diff, lands per-reviewer outputs as Markdown.
#
# Why three? alpha.2 shipped non-functional because Claude alone tested
# only the dev-venv path. Codex caught that. Round-2 Codex flagged a
# Gemini-shaped concern. Round-2 Gemini flagged a Codex-shaped concern.
# No single reviewer is sufficient — they have different blind spots.
#
# Usage:
#     scripts/triple_review.sh                # diff against origin/main
#     scripts/triple_review.sh v0.1.0-alpha.3 # diff against given ref
#     BASE=v0.1.0-alpha.3 scripts/triple_review.sh
#
# Outputs:
#     reviews/<sha>.codex.md
#     reviews/<sha>.gemini.md
#     reviews/<sha>.claude.md
#     reviews/<sha>.summary.md   (cross-references all three)
#
# Requires: codex, gemini, claude CLIs on PATH; git working tree clean.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

BASE="${1:-${BASE:-origin/main}}"
HEAD_SHA="$(git rev-parse --short HEAD)"
HEAD_REF="$(git rev-parse --abbrev-ref HEAD)"
REVIEWS_DIR="reviews"
mkdir -p "$REVIEWS_DIR"

OUT_CODEX="$REVIEWS_DIR/${HEAD_SHA}.codex.md"
OUT_GEMINI="$REVIEWS_DIR/${HEAD_SHA}.gemini.md"
OUT_CLAUDE="$REVIEWS_DIR/${HEAD_SHA}.claude.md"
OUT_SUMMARY="$REVIEWS_DIR/${HEAD_SHA}.summary.md"

DIFF_FILE="$(mktemp /tmp/review-diff.XXXXXX.patch)"
trap 'rm -f "$DIFF_FILE"' EXIT

# --- Generate the diff ---------------------------------------------------
echo "==> Generating diff: $BASE..HEAD ($HEAD_SHA on $HEAD_REF)"
git diff "$BASE..HEAD" -- 'src/' 'packaging/' 'tests/' 'tools/' \
    > "$DIFF_FILE" || true
DIFF_LINES=$(wc -l < "$DIFF_FILE")
echo "    diff: $DIFF_LINES lines"
if [ "$DIFF_LINES" -eq 0 ]; then
    echo "    no changes — nothing to review"
    exit 0
fi

# --- Build the shared review prompt --------------------------------------
PROMPT_FILE="$(mktemp /tmp/review-prompt.XXXXXX.txt)"
trap 'rm -f "$DIFF_FILE" "$PROMPT_FILE"' EXIT

cat > "$PROMPT_FILE" <<EOF
You are reviewing a Git diff on the OpenLimno project (open-source water-
ecology modeling, successor to PHABSIM/River2D/FishXing). The diff range
is $BASE..$HEAD_SHA on branch $HEAD_REF.

Read the unified diff supplied below (~$DIFF_LINES lines), then evaluate.
Cover:

1. Architecture — is the change consistent with what the rest of the
   codebase does? Any unjustified new abstraction?
2. Bug risk — what corner cases are missed? Race conditions, path
   traversal, integer overflow, CRS mismatches, file-handle leaks?
3. Test adequacy — what's NOT covered? Could a regression here pass
   the new tests? What minimum extra coverage would you require?
4. Performance — any O(n^2) hot paths, memory leaks, blocking I/O on
   the GUI thread?
5. Packaging / portability — anything in the build that won't reproduce
   on a clean GitHub Actions runner?
6. Security — anything user-supplied that gets concatenated into shell,
   SQL, or HTTP? Privileged file overwrites? Symlink TOCTOU?

Be specific. Cite file:line where relevant. Do NOT praise. List real
concerns only. Cap at ~600 words.
EOF

# --- Run all three reviewers in parallel ---------------------------------
echo "==> Launching Codex, Gemini, Claude in parallel..."

(
    set +e
    {
        echo "# Codex review — \`$BASE..$HEAD_SHA\`"
        echo
        echo "_Generated by \`codex review --base $BASE\` on $(date -Iseconds)_"
        echo
        codex review --base "$BASE" --title "Triple-review: $HEAD_REF $HEAD_SHA" 2>&1
    } > "$OUT_CODEX"
) &
PID_CODEX=$!

(
    set +e
    {
        echo "# Gemini review — \`$BASE..$HEAD_SHA\`"
        echo
        echo "_Generated by \`gemini -p\` on $(date -Iseconds)_"
        echo
        gemini -p "$(cat "$PROMPT_FILE")" < "$DIFF_FILE" 2>&1
    } > "$OUT_GEMINI"
) &
PID_GEMINI=$!

(
    set +e
    {
        echo "# Claude review — \`$BASE..$HEAD_SHA\`"
        echo
        echo "_Generated by \`claude -p\` on $(date -Iseconds)_"
        echo
        # Two modes:
        #   * CI-style (ANTHROPIC_API_KEY set): --bare for hermetic, stateless
        #     invocation. Skips keychain / hooks / plugin sync. Required for
        #     reproducible review on a clean GitHub Actions runner.
        #   * Local-style (no API key): rely on the user's logged-in session.
        # Either way we feed the prompt + diff via stdin (NOT argv) so we
        # don't hit ARG_MAX on big diffs.
        if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
            CLAUDE_FLAGS=(-p --bare --add-dir "$REPO_ROOT")
        else
            CLAUDE_FLAGS=(-p --add-dir "$REPO_ROOT")
        fi
        {
            cat "$PROMPT_FILE"
            echo
            echo "Diff to review:"
            echo '```diff'
            cat "$DIFF_FILE"
            echo '```'
        } | claude "${CLAUDE_FLAGS[@]}" 2>&1
    } > "$OUT_CLAUDE"
) &
PID_CLAUDE=$!

# Wait for all three (don't fail-fast — we want partial results)
wait $PID_CODEX || echo "    codex returned non-zero (ok if review still wrote)"
wait $PID_GEMINI || echo "    gemini returned non-zero (ok if review still wrote)"
wait $PID_CLAUDE || echo "    claude returned non-zero (ok if review still wrote)"

echo "==> Reviews written:"
for f in "$OUT_CODEX" "$OUT_GEMINI" "$OUT_CLAUDE"; do
    [ -s "$f" ] && echo "    ✓ $f ($(wc -l < "$f") lines)" || echo "    ✗ $f (empty)"
done

# --- Summary ------------------------------------------------------------
{
    echo "# Triple-AI review — $BASE..$HEAD_SHA"
    echo
    echo "_$(git log -1 --pretty=format:'%s' HEAD)_"
    echo
    echo "_Generated $(date -Iseconds) on \`$(uname -s) $(uname -r)\`_"
    echo
    echo "## Reviewers"
    echo
    echo "| AI | output | lines |"
    echo "| --- | --- | --- |"
    for f in "$OUT_CODEX" "$OUT_GEMINI" "$OUT_CLAUDE"; do
        ai=$(echo "$f" | sed 's|.*\.\([^.]*\)\.md|\1|')
        if [ -s "$f" ]; then
            echo "| ${ai^} | [\`${f#reviews/}\`](${f#reviews/}) | $(wc -l < "$f") |"
        else
            echo "| ${ai^} | _(failed)_ | 0 |"
        fi
    done
    echo
    echo "## Diff scope"
    echo
    echo "- Range: \`$BASE..$HEAD_SHA\`"
    echo "- Lines: $DIFF_LINES"
    echo "- Files touched:"
    git diff --name-only "$BASE..HEAD" -- 'src/' 'packaging/' 'tests/' 'tools/' \
        | sed 's/^/  - /'
    echo
    echo "## Reading order"
    echo
    echo "1. Each reviewer above sees the same diff with the same prompt."
    echo "2. Read all three before triaging — they have different blind spots."
    echo "3. Lessons from past rounds: Claude tested only dev-venv → Codex caught"
    echo "   bundle regressions. Codex assumed live network → Gemini caught it."
    echo "   Three reviewers ≠ overkill, it's structurally necessary."
} > "$OUT_SUMMARY"

echo "==> Summary: $OUT_SUMMARY"
echo
echo "Done. Skim: cat $OUT_SUMMARY"
